- name: copio il nuovo file checkdf.sh
  copy:
     backup: true
     owner: reicom
     group: contact
     mode: 0755
     dest: "{{ dest_script }}"
     src: files/checkdf.sh

- name: rimuovo la vecchia riga di cron
  lineinfile:
    backup: true
    path: "{{ dest_cron }}"
    state: absent
    regexp: 'checkdf' 
    
- name: Aggiungo la variabile PERCENTAGE  
  lineinfile:
    path: "{{ dest_cron }}"
    line: "PERCENTAGE={{ default_percentage }}"
  
  
    
- name: aggiungo cron1
  cron: 
     user: reicom
     job: "{{ cron_line }}"
     cron_file: "{{ dest_cron }}"
     name: 'BUG6594_cron1'
     hour: 0
     minute: 0-9/1

- name: aggiungo cron2
  cron: 
     user: reicom
     job: "{{ cron_line }}"
     cron_file: "{{ dest_cron }}"
     name: 'BUG6594_cron2'
     hour: 0
     minute: 15-59/1

- name: aggiungo cron3
  cron: 
     user: reicom
     job: "{{ cron_line }}"
     cron_file: "{{ dest_cron }}"
     name: 'BUG6594_cron3'
     hour: 1-23  
     
- name: aggiungo il file di logrotate
  copy:
    src: files/checkdf.rotate
    dest: /etc/logrotate.d/
    owner: root
    group: root
    mode: 0644             
    